file:C:/Users/amwri/AppData/Local/Programs/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Users/amwri/AppData/Local/Programs/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/amwri/AppData/Local/Programs/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/amwri/AppData/Local/Programs/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Users/amwri/AppData/Local/Programs/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Users/amwri/AppData/Local/Programs/Git/etc/gitconfig	http.sslbackend=openssl
file:C:/Users/amwri/AppData/Local/Programs/Git/etc/gitconfig	http.sslcainfo=C:/Users/amwri/AppData/Local/Programs/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Users/amwri/AppData/Local/Programs/Git/etc/gitconfig	core.autocrlf=true
file:C:/Users/amwri/AppData/Local/Programs/Git/etc/gitconfig	core.fscache=true
file:C:/Users/amwri/AppData/Local/Programs/Git/etc/gitconfig	core.symlinks=false
file:C:/Users/amwri/AppData/Local/Programs/Git/etc/gitconfig	core.editor="C:\\Program Files (x86)\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
file:C:/Users/amwri/AppData/Local/Programs/Git/etc/gitconfig	pull.rebase=false
file:C:/Users/amwri/AppData/Local/Programs/Git/etc/gitconfig	credential.helper=manager-core
file:C:/Users/amwri/AppData/Local/Programs/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/Users/amwri/AppData/Local/Programs/Git/etc/gitconfig	init.defaultbranch=main
file:C:/Users/amwri/.gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/amwri/.gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/amwri/.gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Users/amwri/.gitconfig	filter.lfs.required=true
file:C:/Users/amwri/.gitconfig	user.name=amwright73
file:C:/Users/amwri/.gitconfig	user.email=54158731+amwright73@users.noreply.github.com
